Adding config_from_example.sh to convert config-example.toml to config.toml Adding pre and post install scripts. Creating casper user and group for service.

diff --git a/resources/maintainer_scripts/debian/postinst b/resources/maintainer_scripts/debian/postinst
--- a/resources/maintainer_scripts/debian/postinst
+++ b/resources/maintainer_scripts/debian/postinst
@@ -1,7 +1,43 @@
 #!/usr/bin/env bash
+set -e
 
+# Default Variables
+# ---
+DEFAULT_USERNAME="casper"
+DEFAULT_CONFIG_DIRECTORY="/etc/${DEFAULT_USERNAME}"
+DEFAULT_DATA_DIRECTORY="/var/lib/${DEFAULT_USERNAME}"
+
+# User Creation
+# ---
+# Assure DEFAULT_USERNAME user exists
+if id -u ${DEFAULT_USERNAME} >/dev/null 2>&1; then
+    echo "User ${DEFAULT_USERNAME} already exists."
+else
+    adduser --no-create-home --group --system ${DEFAULT_USERNAME}
+fi
+
+CONFIG_SCRIPT="/etc/casper/config_from_example.sh"
 # create config.toml from config-example.toml
-/etc/casper/config_from_example.sh
+if [[ -f ${CONFIG_SCRIPT} ]]; then
+  exec su -u casper $CONFIG_SCRIPT
+else
+  echo "${CONFIG_SCRIPT} not found."
+  exit 1
+fi
 
 # run pull_genesis script to get latest files
-/etc/casper/pull_genesis.sh
+PULL_GENESIS_SCRIPT="/etc/casper/pull_genesis.sh"
+# create config.toml from config-example.toml
+if [[ -f ${PULL_GENESIS_SCRIPT} ]]; then
+  exec PULL_GENESIS_SCRIPT
+else
+  echo "${PULL_GENESIS_SCRIPT} not found."
+  exit 1
+fi
+
+# Take ownership of directories and files installed
+chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_DATA_DIRECTORY}
+chown -R ${DEFAULT_USERNAME}:${DEFAULT_USERNAME} ${DEFAULT_CONFIG_DIRECTORY}
+
+# This is required for replacement to insert scripts for systemd by cargo-deb
+#DEBHELPER#
